FROM opensuse/tumbleweed

RUN zypper install -y \
    gstreamer \
    gstreamer-plugins-base \
    gstreamer-plugins-good \
    gstreamer-plugins-bad \
    gstreamer-plugins-ugly \
    gstreamer-plugins-rs \
    gstreamer-devel \
    gstreamer-libnice
